# Generated by Django 5.1.3 on 2024-12-02 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='production__name_fcb4a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=10, verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='Транслит')),
                ('proteins', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Белки')),
                ('fats', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Жиры')),
                ('shelf_life', models.IntegerField(max_length=2, verbose_name='Срок годности в мес.')),
                ('gost', models.CharField(max_length=100, verbose_name='ГОСТ/ТУ')),
                ('halal', models.BooleanField(default=True, verbose_name='Халяль')),
                ('ean_13', models.BooleanField(default=False)),
                ('barcode_e13', models.CharField(max_length=13, verbose_name='ШК от заказчика')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='production.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='production__id_e80d7c_idx'), models.Index(fields=['article'], name='production__article_cba85e_idx'), models.Index(fields=['name'], name='production__name_a0c6b7_idx'), models.Index(fields=['-created'], name='production__created_770081_idx')],
            },
        ),
    ]
