# Generated by Django 5.1.3 on 2024-12-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_product_shelf_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_e13',
            field=models.CharField(default='', max_length=13, verbose_name='ШК от заказчика'),
        ),
    ]
