# Generated by Django 5.1.3 on 2024-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_product_barcode_e13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_e13',
            field=models.CharField(max_length=13, verbose_name='ШК от заказчика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='halal',
            field=models.BooleanField(default=False, verbose_name='Халяль'),
        ),
    ]
