# Generated by Django 5.1.3 on 2024-12-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_product_barcode_e13_alter_product_halal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_e13',
            field=models.CharField(blank=True, max_length=13, verbose_name='ШК от заказчика'),
        ),
    ]
