# Generated by Django 5.1.3 on 2024-12-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polutushi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_number', models.CharField(blank=True, max_length=15, verbose_name='Ушной Номер')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weighing_datetime', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='polutushi/%Y/%m/%d', verbose_name='Изображение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['weighing_datetime'],
                'indexes': [models.Index(fields=['weighing_datetime'], name='polutushi_p_weighin_687c56_idx'), models.Index(fields=['ear_number'], name='polutushi_p_ear_num_3f4f84_idx')],
            },
        ),
    ]
